require "colorize"

puts "▕▔╲┊┊┊┊┊┊┊╱▔▏┊┊┊".colorize(:yellow)
puts "┊╲╱╲┊┊┊┊┊╱╲╱┊┊┊┊".colorize(:yellow)
puts "┊┊╲┈╲▂▂▂╱┈╱┊┊┊╱╲".colorize(:yellow)
puts "┊┊╱┈┈┈┈┈┈┈╲┊┊╱┈┈╲".colorize(:yellow)
puts "┊┊▏▕▆▍▂▕▆▍▕┊╱┈┈┈╱".colorize(:yellow)
puts "┊▕╭╮┈┳┻┳┈╭╮▏╲┈┈╱".colorize(:yellow)
puts "┊┊╲╯┈╰━╯┈╰╱┊╱┈┈╲".colorize(:yellow)
puts "┊┊╱┈┈┈┈┈┈┈╲┊╲┈┈┈╲".colorize(:yellow)
puts "┊▕╲┈▕┈┈┈▏┈╱▏┊╱┈╱".colorize(:yellow)
puts "┊▕┈▔▔┈┈┈▔▔┈▏╱┈╱┊".colorize(:yellow)
puts "┊▕┈┈┈┈┈┈┈┈▕▔┈╱┊┊".colorize(:yellow)
puts "┈┈╲┈┈┈┈┈┈┈╱▔▔┈┈┈".colorize(:yellow)
puts "┈┈▕▂╱▔▔▔╲▂▏┈┈┈┈┈".colorize(:yellow)
